export const STRINGS = {
  welcome: {
    title: "cornr",
    subtitle: "Every corner, considered.",
    headline: "Find your home style in 60 seconds.",
    cta: "Get started",
    signIn: "Already have an account? Sign in",
  },
  signUp: {
    title: "Create your account",
    emailLabel: "Email address",
    passwordLabel: "Password",
    ageCheckbox: "I confirm I am 18 years or older",
    submitButton: "Create account",
    hasAccount: "Already have an account?",
    signInLink: "Sign in",
    ageError: "You must be 18 or older to use Cornr",
    passwordHint: "At least 8 characters",
    privacyPolicy: "By creating an account you agree to our",
    privacyPolicyLink: "Privacy Policy",
    privacyPolicyNotice: "Privacy policy will be available at cornr.co.uk/privacy before launch",
    checkEmail: "Check your email to continue.",
    genericError: "Something went wrong. Please try again.",
  },
  signIn: {
    title: "Welcome back",
    emailLabel: "Email address",
    passwordLabel: "Password",
    submitButton: "Sign in",
    forgotPassword: "Forgot your password?",
    noAccount: "Don't have an account?",
    signUpLink: "Sign up",
    resetTitle: "Reset your password",
    resetDescription: "Enter your email and we'll send you a reset link",
    resetButton: "Send reset link",
    resetSuccess: "Check your email for a reset link.",
    backToSignIn: "Back to sign in",
    emailInvalid: "Please enter a valid email address",
    genericError: "Something went wrong. Please try again.",
  },
  tabs: {
    home: "Home",
    products: "Products",
    trades: "Trades",
    profile: "Profile",
  },
  home: {
    title: "Your Home",
    emptyIcon: "DoorOpen",
    emptyHeadline: "Your home, waiting to become yours.",
    emptySubtext: "Add your first room to get started.",
    emptyCta: "Add a room",
    secondRoomPrompt: "Ready to style another room? Adding a second room helps Cornr understand your whole home.",
    secondRoomCta: "Add another room",
  },
} as const;
